@startuml
left to right direction
actor "Producer" as producer
actor "Consumer" as consumer

rectangle fifo {
  usecase "put" as put
  usecase "get" as get
  usecase "reset" as reset
  usecase "is_empty" as is_empty
  usecase "is_full" as is_full
}

producer --> put
producer --> reset
consumer <-- get
consumer <-- is_empty
consumer <-- is_full
@enduml

